name: Nix

on:
  push:
  workflow_dispatch:

permissions:
  contents: "read"

env:
  NIX_ABORT_ON_WARN: "1"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: DeterminateSystems/determinate-nix-action@629b284231c2a82554b724e357e47fc6020833c8 # v3.21.2

      - uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14

      - name: Check flake
        run: |
          nix flake check --keep-going --print-build-logs github:${{ github.repository }}/${{ github.sha }}

      - name: Build ISOs
        run: |
          nix build --keep-going --print-build-logs github:${{ github.repository }}/${{ github.sha }}#all-isos
