name: Release

on:
  push:
    tags:
      - "*"

permissions:
  id-token: "write"
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - uses: DeterminateSystems/determinate-nix-action@73327eb48f028efaaf5013656ba216ca3cdeca7b # v3.16.3

      - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build ISOs
        run: |
          nix build --keep-going --print-build-logs github:${{ github.repository }}/${{ github.sha }}#all-isos

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{ github.ref_name }}
        run: |
          gh release create "$VERSION" --title="$VERSION" result/*.iso
